name: Tests

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend 

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - run: npm install 
      - run: npm run test
  build2:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - run: npm install 
      - run: npm run test
